# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e0e88d2f5408acd78a24a5b47e534d0c"
application_url = "https://contract-symbols-showed-trying.trycloudflare.com"
embedded = true
name = "appdemo"
handle = "appdemo-39"

[build]
include_config_on_deploy = true
dev_store_url = "hungstore-vn.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://contract-symbols-showed-trying.trycloudflare.com/auth/callback",
  "https://contract-symbols-showed-trying.trycloudflare.com/auth/shopify/callback",
  "https://contract-symbols-showed-trying.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
