# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c136d7036949bd433ebcb64deb6977c9"
application_url = "https://obj-financial-presentations-stick.trycloudflare.com"
embedded = true
name = "Billing User"
handle = "billing-user"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://obj-financial-presentations-stick.trycloudflare.com/auth/callback",
  "https://obj-financial-presentations-stick.trycloudflare.com/auth/shopify/callback",
  "https://obj-financial-presentations-stick.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "hungstore-vn.myshopify.com"
automatically_update_urls_on_dev = true
